#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service einrcore stop || echo "einrcore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "einrcore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "einrcore.service" || echo "einrcore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so einrcore could not be stopped"
fi
